### ISSUE TITLE
1.0.1版报错 unexpected end of file at summernote/src/Editor.php 52

### ISSUE THREAD

**Issue by joseph-bing-han** [laravel-admin-extensions/summernote#16]
系统：Ubuntu Server 5.4.0-87-generic #98~18.04.1-Ubuntu SMP Wed Sep 22 10:45:04 UTC 2021 x86_64
PHP：PHP 7.2.24-0ubuntu0.18.04.9
![2021-10-12-174429](https://user-images.githubusercontent.com/1439426/136906183-dc97e3db-cec1-4a14-a4eb-d51347413738.png)

**Comment by ArrowJustDoIt** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
